# Starter pipeline

  
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      docker pull zeronorth/integration
      docker run -e CYBRIC_USER=raman.sharma -e CYBRIC_PASSWORD=Indianarmy2021 zeronorth/integration:latest python scenarios.py
